{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5d297a31-494d-4ee3-ac0a-58afc007959f",
   "metadata": {},
   "source": [
    "## Identify leading edge\n",
    "\n",
    "This is a test notebook, for me to make a few tests about leading edge detection on along track altimeter Waveforms.\n",
    "\n",
    "The algo is an implementation of the leading edge detection of WHALES algo described in [this document](https://climate.esa.int/sites/default/files/Sea_State_cci_ATBD_v1.1-signed_0.pdf)\n",
    "\n",
    "For now it is random code, with 0 optims consideration: \n",
    "- for loops in numpy arrays instead of using vectorized numpy functions (derivative)\n",
    "- dask distribution with micro chunks is inefficient\n",
    "\n",
    "But the objective here is to load zarr time ranges that have not been processed (zarr partitionned by time range) and to use chunks defined at zarr level. \n",
    "Zarr variable we use as input is *waveform_20_plrm_ku*, which is 20Hz data, with 128 waveform points per waveform. This variable is 2D, indexed by *time_20_c* (timestamp of the waveform) and *echo_sample_ind* (index of each of the 128 waveform data points).\n",
    "Idealy, chunks are in the MBs range, so that it is worth using dask.\n",
    "\n",
    "On each chunk, we have multiple waveforms on which we apply the leading_edge detection algorithm sequentially, to derive *startgate* and *stopgate* attributes of the waveform. And chunks are processed in parallel via dask.\n",
    "\n",
    "Then the *startgate* and *stopgate* are stored to variables *waveform_20_plrm_ku_startgate* and *waveform_20_plrm_ku_stopgate* which are tied to index *time_20_c*.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "24695572-e042-434d-b2f2-108357be01e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "import os\n",
    "import sys\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "import dask\n",
    "import dask.distributed\n",
    "import dask.array as da\n",
    "import zcollection\n",
    "\n",
    "from typing import Tuple, Optional\n",
    "\n",
    "import eumdac.collection\n",
    "\n",
    "sys.path.append(os.path.abspath('..'))\n",
    "from src.connectors.eumdac_connector import EumdacConnector\n",
    "from src.processors.zarr_processor import ZarrProcessor\n",
    "from utils.logging_utils import setup_root_logging, setup_module_logger\n",
    "from utils.opensearch_query_formatter import OpenSearchQueryFormatter"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef01e5a7-d250-490b-9225-d0123ac0c75a",
   "metadata": {},
   "source": [
    "### The Leading edge detection algo - to apply on one waveform\n",
    "\n",
    "To refacto - use numpy better"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "18921e91-faa5-4122-a4da-4d35122ff2d4",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "array() missing required argument 'object' (pos 0)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21midentify_leading_edge\u001b[39m(waveform: np\u001b[38;5;241m.\u001b[39marray, tau: \u001b[38;5;28mfloat\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m np\u001b[38;5;241m.\u001b[39marray():\n\u001b[1;32m      2\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;124;03m    Identify the startgate and stopgate of a waveform.\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;124;03m    From algo described here: https://climate.esa.int/sites/default/files/Sea_State_cci_ATBD_v1.1-signed_0.pdf\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     12\u001b[0m \n\u001b[1;32m     13\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m     14\u001b[0m     res: np\u001b[38;5;241m.\u001b[39marray \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39marray([\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1.0\u001b[39m, \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1.0\u001b[39m], dtype\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mfloat64)\n",
      "\u001b[0;31mTypeError\u001b[0m: array() missing required argument 'object' (pos 0)"
     ]
    }
   ],
   "source": [
    "def identify_leading_edge(waveform: np.array, tau: float) -> np.array():\n",
    "    \"\"\"\n",
    "    Identify the startgate and stopgate of a waveform.\n",
    "    From algo described here: https://climate.esa.int/sites/default/files/Sea_State_cci_ATBD_v1.1-signed_0.pdf\n",
    "\n",
    "    :param np.array waveform: numpy array of waveform values\n",
    "    :param float tau: time spacing between consecutive gates in seconds\n",
    "    :return: 1D np.array with 2 values:\n",
    "      - startgate: index of the start gate (Optional[int])\n",
    "      - stopgate: index of the stop gate (Optional[int])\n",
    "    :rtype: np.array\n",
    "\n",
    "    \"\"\"\n",
    "    res: np.array = np.array([-1.0, -1.0], dtype=np.float64)\n",
    "    try:\n",
    "        # The waveform is normalised with normalisation factor N, \n",
    "        # where N = 1.3 * median(waveform)\n",
    "        N: float = 1.3 * np.median(waveform)\n",
    "        normalized_waveform: np.ndarray = waveform / N\n",
    "\n",
    "        # Calculate the waveform derivative\n",
    "        derivatives: np.array = np.diff(normalized_waveform)\n",
    "        \n",
    "        # The leading edge starts when the normalised waveform has a \n",
    "        # rise of 0.01 units compared to the previous gate (startgate)\n",
    "        startgate_candidates = np.where(np.diff(normalized_waveform) >= 0.01)[0] + 1\n",
    "        \n",
    "        if startgate_candidates.size == 0:\n",
    "            return res\n",
    "        \n",
    "        startgate = startgate_candidates[0]\n",
    "    \n",
    "        # At this point, the leading edge is considered valid if, for at least four gates \n",
    "        # after startgate, it does not decrease below 0.1 units (10% of the normalised power).\n",
    "        valid_startgate: bool = (\n",
    "            startgate + 4 < len(normalized_waveform) and\n",
    "            np.all(normalized_waveform[startgate:startgate + 5] >= 0.1)\n",
    "        )\n",
    "        \n",
    "        if not valid_startgate:\n",
    "            return res  # startgate is not valid\n",
    "    \n",
    "        # The end of the leading edge (stopgate) is fixed at the first gate \n",
    "        # in which the derivative changes sign (i.e. the signal start decreasing \n",
    "        # and the trailing edge begins), if the change of sign is kept \n",
    "        # for the following 3 gates.\n",
    "        stopgate_candidates = np.where((derivatives[:-1] > 0) & (derivatives[1:] < 0))[0] + 1\n",
    "\n",
    "        # Ensure the stopgate is valid (check the next three gates)\n",
    "        for stopgate in stopgate_candidates:\n",
    "            if (\n",
    "                stopgate + 3 < len(normalized_waveform) and \n",
    "                np.all(derivatives[stopgate:stopgate + 3] < 0)\n",
    "            ):\n",
    "                res = np.array([startgate, stopgate], dtype=np.float64)\n",
    "                return res\n",
    "                \n",
    "        # Return default startgate/stopdate if no valid leading edge found\n",
    "        return res\n",
    "    except:\n",
    "        return res"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "60c64a07-31ef-4afd-b595-e9901fce297d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ 4. 10.]\n",
      "Startgate: 4.0, Stopgate: 10.0\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    # Simulated waveform data\n",
    "    waveform: np.ndarray = np.array([0.0, 0.0, 0.0, 0.0001, 0.0015, 0.002, 0.004, 0.01, 0.02, 0.05, 0.15, 0.1, 0.08, 0.07, 0.03, 0.01, 0.0])\n",
    "    tau: float = 3.125e-9  # Time spacing in seconds\n",
    "\n",
    "    res = identify_leading_edge(waveform, tau)\n",
    "    print(res)\n",
    "    startgate, stopgate = res\n",
    "    print(f\"Startgate: {startgate}, Stopgate: {stopgate}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "abfb26f7-0dbf-4d6e-b0b1-d3df41f8f091",
   "metadata": {},
   "source": [
    "### Download datasets containing waveform (Sentinel 3) and store them to zarr\n",
    "\n",
    "**TODO**: zarr storage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "63f09d4e-c112-47eb-a7ba-332b0c896f07",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-06 09:46:06.737 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 13 | Connecting EUMDAC datastore...\n",
      "2024-10-06 09:46:06.979 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 25 | Listing EUMDAC products matching filters 'pi=EO:EUM:DAT:0415&dtstart=2024-09-23T00:00:00Z&dtend=2024-09-23T00:20:00Z'\n",
      "2024-10-06 09:46:08.001 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 30 | Local mode: processing every 50th product to debug faster\n",
      "2024-10-06 09:46:08.002 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 32 | 10 matching products found\n",
      "2024-10-06 09:46:08.003 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 36 | Downloading products (dask parallelized)...\n",
      "2024-10-06 09:46:08.612 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | src.connectors.eumdac_connector download_products eumdac_connector.py:177 | Downloading products...\n",
      "2024-10-06 09:46:24.334 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | __main__ <module> 2893144178.py: 43 | Persisting data in a partitionned zarr collection...\n",
      "2024-10-06 09:46:24.363 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | src.processors.zarr_processor netcdf_2_zarr zarr_processor.py:155 | Loading every netcdf files to a xr.Dataset...\n",
      "2024-10-06 09:46:26.360 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | src.processors.zarr_processor netcdf_2_zarr zarr_processor.py:167 | Concat datasets to a single distributed xr.Dataset...\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<xarray.Dataset> Size: 55MB\n",
      "Dimensions:              (time_20_c: 52706, echo_sample_ind: 128)\n",
      "Coordinates:\n",
      "  * time_20_c            (time_20_c) datetime64[ns] 422kB 2024-09-22T23:33:26...\n",
      "  * echo_sample_ind      (echo_sample_ind) int8 128B 0 1 2 3 ... 124 125 126 127\n",
      "    lat_20_c             (time_20_c) float64 422kB ...\n",
      "    lon_20_c             (time_20_c) float64 422kB ...\n",
      "Data variables:\n",
      "    waveform_20_plrm_ku  (time_20_c, echo_sample_ind) float64 54MB ...\n",
      "Attributes: (12/64)\n",
      "    Conventions:                                 CF-1.6\n",
      "    title:                                       IPF SRAL/MWR Level 2 Measure...\n",
      "    mission_name:                                Sentinel 3A\n",
      "    altimeter_sensor_name:                       SRAL\n",
      "    radiometer_sensor_name:                      MWR\n",
      "    gnss_sensor_name:                            GNSS\n",
      "    ...                                          ...\n",
      "    algo_bias_wind_speed_sig0_sar_ku_added:      -0.0413\n",
      "    algo_bias_wind_speed_2p_sig0_sar_ku_added:   2.744\n",
      "    algo_bias_wind_speed_2p_swh_sar_ku_added:    0.0\n",
      "    algo_bias_wind_speed_sig0_plrm_ku_added:     -0.0382\n",
      "    algo_bias_wind_speed_2p_sig0_plrm_ku_added:  2.7525\n",
      "    algo_bias_wind_speed_2p_swh_plrm_ku_added:   0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-06 09:46:31.053 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | zcollection.collection from_config __init__.py:283 | Opening collection: '/tmp/sen3_sral_enhanced'\n",
      "2024-10-06 09:46:31.054 INFO     | 127.0.1.1 PID:7910 TID:139861990331456 | src.processors.zarr_processor _open_or_create_collection zarr_processor.py:110 | zcollection at /tmp/sen3_sral_enhanced not found, creating it\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "The variable 'time_20_ku' is not defined in the dataset.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "File \u001b[0;32m~/repo/sentinel3-sral-demo/src/processors/zarr_processor.py:106\u001b[0m, in \u001b[0;36mZarrProcessor._open_or_create_collection\u001b[0;34m(self, zarr_data_set)\u001b[0m\n\u001b[1;32m    105\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 106\u001b[0m     collection \u001b[38;5;241m=\u001b[39m zcollection\u001b[38;5;241m.\u001b[39mopen_collection(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mzarr_collection_path, mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mw\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    107\u001b[0m     logger\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mUsing existing zcollection at \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mzarr_collection_path)\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/zcollection/convenience/collection.py:88\u001b[0m, in \u001b[0;36mopen_collection\u001b[0;34m(path, mode, **kwargs)\u001b[0m\n\u001b[1;32m     73\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Open a collection.\u001b[39;00m\n\u001b[1;32m     74\u001b[0m \n\u001b[1;32m     75\u001b[0m \u001b[38;5;124;03mArgs:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     86\u001b[0m \u001b[38;5;124;03m    ...     \"/tmp/mycollection\", mode=\"r\")\u001b[39;00m\n\u001b[1;32m     87\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m---> 88\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m collection\u001b[38;5;241m.\u001b[39mCollection\u001b[38;5;241m.\u001b[39mfrom_config(path, mode\u001b[38;5;241m=\u001b[39mmode, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/zcollection/collection/__init__.py:287\u001b[0m, in \u001b[0;36mCollection.from_config\u001b[0;34m(cls, path, mode, filesystem, synchronizer)\u001b[0m\n\u001b[1;32m    286\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m fs\u001b[38;5;241m.\u001b[39mexists(config):\n\u001b[0;32m--> 287\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mzarr collection not found at path \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mpath\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m    288\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m fs\u001b[38;5;241m.\u001b[39mopen(config) \u001b[38;5;28;01mas\u001b[39;00m stream:\n",
      "\u001b[0;31mValueError\u001b[0m: zarr collection not found at path '/tmp/sen3_sral_enhanced'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 56\u001b[0m\n\u001b[1;32m     47\u001b[0m partition_handler: zcollection\u001b[38;5;241m.\u001b[39mpartitioning\u001b[38;5;241m.\u001b[39mPartitioning \u001b[38;5;241m=\u001b[39m zcollection\u001b[38;5;241m.\u001b[39mpartitioning\u001b[38;5;241m.\u001b[39mDate(\n\u001b[1;32m     48\u001b[0m     (INDEX_DIMENSION,), resolution\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mM\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     49\u001b[0m )\n\u001b[1;32m     51\u001b[0m zarr_processor: ZarrProcessor \u001b[38;5;241m=\u001b[39m ZarrProcessor(\n\u001b[1;32m     52\u001b[0m     ZARR_BASE_PATH, \n\u001b[1;32m     53\u001b[0m     partition_handler, \n\u001b[1;32m     54\u001b[0m     index_dimension\u001b[38;5;241m=\u001b[39mINDEX_DIMENSION,\n\u001b[1;32m     55\u001b[0m )\n\u001b[0;32m---> 56\u001b[0m zarr_processor\u001b[38;5;241m.\u001b[39mnetcdf_2_zarr(\n\u001b[1;32m     57\u001b[0m     netcdf_file_paths,\n\u001b[1;32m     58\u001b[0m     variables \u001b[38;5;241m=\u001b[39m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mwaveform_20_plrm_ku\u001b[39m\u001b[38;5;124m\"\u001b[39m], \u001b[38;5;66;03m# only extract waveform_20_plrm_ku\u001b[39;00m\n\u001b[1;32m     59\u001b[0m     chunk_size\u001b[38;5;241m=\u001b[39m(\u001b[38;5;241m5000\u001b[39m,) \u001b[38;5;66;03m# About 4mn chunks at 50Hz with int32 values- 2MB\u001b[39;00m\n\u001b[1;32m     60\u001b[0m )\n\u001b[1;32m     61\u001b[0m logger\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mJob done\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/repo/sentinel3-sral-demo/src/processors/zarr_processor.py:173\u001b[0m, in \u001b[0;36mZarrProcessor.netcdf_2_zarr\u001b[0;34m(self, netcdf_file_paths, variables, chunk_size)\u001b[0m\n\u001b[1;32m    169\u001b[0m combined_data \u001b[38;5;241m=\u001b[39m combined_data\u001b[38;5;241m.\u001b[39msortby(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mindex_dimension)\n\u001b[1;32m    171\u001b[0m zds: zcollection\u001b[38;5;241m.\u001b[39mDataset \u001b[38;5;241m=\u001b[39m zcollection\u001b[38;5;241m.\u001b[39mDataset\u001b[38;5;241m.\u001b[39mfrom_xarray(combined_data)\n\u001b[0;32m--> 173\u001b[0m collection: zcollection\u001b[38;5;241m.\u001b[39mCollection \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_open_or_create_collection(zds)\n\u001b[1;32m    175\u001b[0m logger\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mInserting data to the zarr collection at \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mzarr_collection_path)\n\u001b[1;32m    176\u001b[0m collection\u001b[38;5;241m.\u001b[39minsert(zds, chunk_size\u001b[38;5;241m=\u001b[39mchunk_size)\n",
      "File \u001b[0;32m~/repo/sentinel3-sral-demo/src/processors/zarr_processor.py:113\u001b[0m, in \u001b[0;36mZarrProcessor._open_or_create_collection\u001b[0;34m(self, zarr_data_set)\u001b[0m\n\u001b[1;32m    110\u001b[0m     logger\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mzcollection at \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m not found, creating it\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mzarr_collection_path)\n\u001b[1;32m    111\u001b[0m     filesystem: fsspec\u001b[38;5;241m.\u001b[39mimplementations\u001b[38;5;241m.\u001b[39mlocal\u001b[38;5;241m.\u001b[39mLocalFileSystem \u001b[38;5;241m=\u001b[39m fsspec\u001b[38;5;241m.\u001b[39mfilesystem(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfile\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m--> 113\u001b[0m     collection \u001b[38;5;241m=\u001b[39m zcollection\u001b[38;5;241m.\u001b[39mcreate_collection(\n\u001b[1;32m    114\u001b[0m         axis\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mindex_dimension,\n\u001b[1;32m    115\u001b[0m         ds\u001b[38;5;241m=\u001b[39mzarr_data_set,\n\u001b[1;32m    116\u001b[0m         partition_handler\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpartition_handler,\n\u001b[1;32m    117\u001b[0m         partition_base_dir\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mzarr_collection_path,\n\u001b[1;32m    118\u001b[0m         filesystem\u001b[38;5;241m=\u001b[39mfilesystem,\n\u001b[1;32m    119\u001b[0m     )\n\u001b[1;32m    121\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_collection \u001b[38;5;241m=\u001b[39m collection\n\u001b[1;32m    122\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m collection\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/zcollection/convenience/collection.py:59\u001b[0m, in \u001b[0;36mcreate_collection\u001b[0;34m(axis, ds, partition_handler, partition_base_dir, **kwargs)\u001b[0m\n\u001b[1;32m     57\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(ds, xarray\u001b[38;5;241m.\u001b[39mDataset):\n\u001b[1;32m     58\u001b[0m     ds \u001b[38;5;241m=\u001b[39m dataset\u001b[38;5;241m.\u001b[39mDataset\u001b[38;5;241m.\u001b[39mfrom_xarray(ds)\n\u001b[0;32m---> 59\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m collection\u001b[38;5;241m.\u001b[39mCollection(axis,\n\u001b[1;32m     60\u001b[0m                              ds\u001b[38;5;241m.\u001b[39mmetadata(),\n\u001b[1;32m     61\u001b[0m                              partition_handler,\n\u001b[1;32m     62\u001b[0m                              partition_base_dir,\n\u001b[1;32m     63\u001b[0m                              mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mw\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m     64\u001b[0m                              filesystem\u001b[38;5;241m=\u001b[39mfilesystem,\n\u001b[1;32m     65\u001b[0m                              \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/zcollection/collection/__init__.py:182\u001b[0m, in \u001b[0;36mCollection.__init__\u001b[0;34m(self, axis, ds, partition_handler, partition_base_dir, mode, filesystem, synchronizer)\u001b[0m\n\u001b[1;32m    171\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__init__\u001b[39m(\n\u001b[1;32m    172\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    173\u001b[0m     axis: \u001b[38;5;28mstr\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    180\u001b[0m     synchronizer: sync\u001b[38;5;241m.\u001b[39mSync \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    181\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m--> 182\u001b[0m     \u001b[38;5;28msuper\u001b[39m()\u001b[38;5;241m.\u001b[39m\u001b[38;5;21m__init__\u001b[39m(axis\u001b[38;5;241m=\u001b[39maxis,\n\u001b[1;32m    183\u001b[0m                      ds\u001b[38;5;241m=\u001b[39mds,\n\u001b[1;32m    184\u001b[0m                      partition_handler\u001b[38;5;241m=\u001b[39mpartition_handler,\n\u001b[1;32m    185\u001b[0m                      partition_base_dir\u001b[38;5;241m=\u001b[39mpartition_base_dir,\n\u001b[1;32m    186\u001b[0m                      mode\u001b[38;5;241m=\u001b[39mmode,\n\u001b[1;32m    187\u001b[0m                      filesystem\u001b[38;5;241m=\u001b[39mfilesystem,\n\u001b[1;32m    188\u001b[0m                      synchronizer\u001b[38;5;241m=\u001b[39msynchronizer)\n\u001b[1;32m    190\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmode \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mr\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m    191\u001b[0m         \u001b[38;5;66;03m# pylint: disable=method-hidden\u001b[39;00m\n\u001b[1;32m    192\u001b[0m         \u001b[38;5;66;03m# These methods are overloaded when the collection is opened in\u001b[39;00m\n\u001b[1;32m    193\u001b[0m         \u001b[38;5;66;03m# readonly.\u001b[39;00m\n\u001b[1;32m    194\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_read_only_mode()\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/zcollection/collection/abc.py:205\u001b[0m, in \u001b[0;36mReadOnlyCollection.__init__\u001b[0;34m(self, axis, ds, partition_handler, partition_base_dir, mode, filesystem, synchronizer)\u001b[0m\n\u001b[1;32m    193\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__init__\u001b[39m(\n\u001b[1;32m    194\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    195\u001b[0m     axis: \u001b[38;5;28mstr\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    202\u001b[0m     synchronizer: sync\u001b[38;5;241m.\u001b[39mSync \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    203\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    204\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m axis \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m ds\u001b[38;5;241m.\u001b[39mvariables:\n\u001b[0;32m--> 205\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m    206\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mThe variable \u001b[39m\u001b[38;5;132;01m{\u001b[39;00maxis\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[38;5;124m is not defined in the dataset.\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m    208\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m varname \u001b[38;5;129;01min\u001b[39;00m partition_handler\u001b[38;5;241m.\u001b[39mvariables:\n\u001b[1;32m    209\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m varname \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m ds\u001b[38;5;241m.\u001b[39mvariables:\n",
      "\u001b[0;31mValueError\u001b[0m: The variable 'time_20_ku' is not defined in the dataset."
     ]
    }
   ],
   "source": [
    "setup_root_logging()\n",
    "\n",
    "logger: logging.Logger = setup_module_logger(__name__)\n",
    "\n",
    "COLLECTION_ID: str = \"EO:EUM:DAT:0415\"\n",
    "DOWNLOAD_DIR: str = \"/tmp/products\"\n",
    "MEASUREMENTS_FILENAME: str = \"enhanced_measurement.nc\"\n",
    "ZARR_BASE_PATH: str = \"/tmp/sen3_sral_enhanced\"\n",
    "INDEX_DIMENSION: str = \"time_20_c\"\n",
    "download_dir: str = os.path.join(os.getcwd(), DOWNLOAD_DIR)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    logger.info(\"Connecting EUMDAC datastore...\")\n",
    "    connector: EumdacConnector = EumdacConnector()\n",
    "    datastore: eumdac.datastore.DataStore = connector.datastore\n",
    "\n",
    "    # Query a few data files for Sentinel3A and 3B SRAL (Level2 data) for 2024-09-20\n",
    "    opensearch_query: str = OpenSearchQueryFormatter(\n",
    "        query_params={\n",
    "            \"pi\": COLLECTION_ID,\n",
    "            \"dtstart\": \"2024-09-23T00:00:00Z\",\n",
    "            \"dtend\": \"2024-09-23T00:20:00Z\",\n",
    "        }\n",
    "    ).format()\n",
    "    logger.info(\"Listing EUMDAC products matching filters '%s'\", opensearch_query)\n",
    "    products: eumdac.collection.SearchResults = datastore.opensearch(query=opensearch_query)\n",
    "    product_ids: list[str] = [str(x) for x in products]\n",
    "    # If in local mode, process only a subset of the products for faster execution\n",
    "    if os.getenv(\"LOCAL_MODE\", \"1\"):\n",
    "        logger.info(\"Local mode: processing every 50th product to debug faster\")\n",
    "        #product_ids = product_ids[::50]\n",
    "    logger.info(\"%s matching products found\", len(product_ids))\n",
    "    logger.debug(\"Listed products are: %s\", product_ids)\n",
    "\n",
    "    # Download files - benefits of dask parallelization\n",
    "    logger.info(\"Downloading products (dask parallelized)...\")\n",
    "    downloaded_folders: list[str] = connector.download_products(\n",
    "        COLLECTION_ID, product_ids, download_dir, MEASUREMENTS_FILENAME\n",
    "    )\n",
    "\n",
    "    # Store files to partitionned zarr files\n",
    "    # Partition by day (with zcollection) - to be tuned depending on data use / volumetry\n",
    "    logger.info(\"Persisting data in a partitionned zarr collection...\")\n",
    "    netcdf_file_paths: list[str] = [\n",
    "        os.path.join(folder, MEASUREMENTS_FILENAME) for folder in downloaded_folders\n",
    "    ]\n",
    "    partition_handler: zcollection.partitioning.Partitioning = zcollection.partitioning.Date(\n",
    "        (INDEX_DIMENSION,), resolution='M'\n",
    "    )\n",
    "\n",
    "    zarr_processor: ZarrProcessor = ZarrProcessor(\n",
    "        ZARR_BASE_PATH, \n",
    "        partition_handler, \n",
    "        index_dimension=INDEX_DIMENSION,\n",
    "    )\n",
    "    zarr_processor.netcdf_2_zarr(\n",
    "        netcdf_file_paths,\n",
    "        variables = [\"waveform_20_plrm_ku\"], # only extract waveform_20_plrm_ku\n",
    "        chunk_size=(5000,) # About 4mn chunks at 50Hz with int32 values- 2MB\n",
    "    )\n",
    "    logger.info(\"Job done\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be87cf22-6554-4a22-bbb9-729de691f897",
   "metadata": {},
   "source": [
    "### WIP\n",
    "\n",
    "To refacto 100%: load from zarr, process bigger chunks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "998c9dc2-0073-4f46-a041-8d557fb91de5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 41935 instead\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<xarray.Dataset> Size: 3MB\n",
      "Dimensions:                                        (time_01: 33,\n",
      "                                                    time_20_ku: 628,\n",
      "                                                    time_20_c: 628,\n",
      "                                                    echo_sample_ind: 128)\n",
      "Coordinates:\n",
      "  * time_01                                        (time_01) datetime64[ns] 264B ...\n",
      "  * time_20_ku                                     (time_20_ku) datetime64[ns] 5kB ...\n",
      "  * time_20_c                                      (time_20_c) datetime64[ns] 5kB ...\n",
      "  * echo_sample_ind                                (echo_sample_ind) int8 128B ...\n",
      "    lat_01                                         (time_01) float64 264B ...\n",
      "    lon_01                                         (time_01) float64 264B ...\n",
      "    lat_20_ku                                      (time_20_ku) float64 5kB ...\n",
      "    lon_20_ku                                      (time_20_ku) float64 5kB ...\n",
      "    lat_20_c                                       (time_20_c) float64 5kB ...\n",
      "    lon_20_c                                       (time_20_c) float64 5kB ...\n",
      "Data variables: (12/392)\n",
      "    UTC_day_01                                     (time_01) datetime64[ns] 264B ...\n",
      "    UTC_sec_01                                     (time_01) float64 264B ...\n",
      "    UTC_day_20_ku                                  (time_20_ku) datetime64[ns] 5kB ...\n",
      "    UTC_sec_20_ku                                  (time_20_ku) float64 5kB ...\n",
      "    UTC_day_20_c                                   (time_20_c) datetime64[ns] 5kB ...\n",
      "    UTC_sec_20_c                                   (time_20_c) float64 5kB ...\n",
      "    ...                                             ...\n",
      "    num_20hz_meas_01_ku                            (time_01) float32 132B ...\n",
      "    num_20hz_meas_01_c                             (time_01) float32 132B ...\n",
      "    orbit_type_01                                  (time_01) float32 132B ...\n",
      "    waveform_qual_ice_20_ku                        (time_20_ku) float32 3kB ...\n",
      "    iono_cor_alt_filtered_01_ku                    (time_01) float64 264B ...\n",
      "    iono_cor_alt_filtered_01_plrm_ku               (time_01) float64 264B ...\n",
      "Attributes: (12/64)\n",
      "    Conventions:                                 CF-1.6\n",
      "    title:                                       IPF SRAL/MWR Level 2 Measure...\n",
      "    mission_name:                                Sentinel 3B\n",
      "    altimeter_sensor_name:                       SRAL\n",
      "    radiometer_sensor_name:                      MWR\n",
      "    gnss_sensor_name:                            GNSS\n",
      "    ...                                          ...\n",
      "    algo_bias_wind_speed_sig0_sar_ku_added:      -0.0008\n",
      "    algo_bias_wind_speed_2p_sig0_sar_ku_added:   2.7735\n",
      "    algo_bias_wind_speed_2p_swh_sar_ku_added:    0.0\n",
      "    algo_bias_wind_speed_sig0_plrm_ku_added:     0.02795\n",
      "    algo_bias_wind_speed_2p_sig0_plrm_ku_added:  2.8071\n",
      "    algo_bias_wind_speed_2p_swh_plrm_ku_added:   0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-05 22:01:19,635 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 95, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(95, 96, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,641 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 90, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(90, 91, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,646 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 86, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(86, 87, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,651 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 85, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(85, 86, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,659 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 83, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(83, 84, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,661 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 84, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(84, 85, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,667 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 82, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(82, 83, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,697 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 74, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(74, 75, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,699 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 72, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(72, 73, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,712 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 93, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(93, 94, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,714 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 87, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(87, 88, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,714 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 88, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(88, 89, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,716 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 81, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(81, 82, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,719 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 68, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(68, 69, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,719 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 73, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(73, 74, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 98, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(98, 99, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 96, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(96, 97, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 8, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(8, 9, None\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,722 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 76, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(76, 77, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,723 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 65, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(65, 66, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,725 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 70, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(70, 71, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,731 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 625, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(625, 626, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,735 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 619, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(619, 620, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,737 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 62, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(62, 63, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,747 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 608, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(608, 609, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,769 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 71, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(71, 72, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,776 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 63, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(63, 64, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,777 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 627, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(627, 628, \n",
      "kwargs:    {}\n",
      "Exception: 'NameE"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'identify_leading_edge' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 23\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;66;03m# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\u001b[39;00m\n\u001b[1;32m     18\u001b[0m result_array \u001b[38;5;241m=\u001b[39m lrm_dda\u001b[38;5;241m.\u001b[39mmap_blocks(\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;66;03m# Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\u001b[39;00m\n\u001b[1;32m     20\u001b[0m     \u001b[38;5;28;01mlambda\u001b[39;00m x: identify_leading_edge(np\u001b[38;5;241m.\u001b[39msqueeze(x), tau),\n\u001b[1;32m     21\u001b[0m     meta\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mzeros(\u001b[38;5;241m2\u001b[39m, dtype\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mfloat64)\n\u001b[1;32m     22\u001b[0m )\n\u001b[0;32m---> 23\u001b[0m result \u001b[38;5;241m=\u001b[39m result_array\u001b[38;5;241m.\u001b[39mcompute()\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28mprint\u001b[39m(result)\n\u001b[1;32m     26\u001b[0m client\u001b[38;5;241m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/base.py:376\u001b[0m, in \u001b[0;36mDaskMethodsMixin.compute\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m    352\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcompute\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    353\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Compute this dask collection\u001b[39;00m\n\u001b[1;32m    354\u001b[0m \n\u001b[1;32m    355\u001b[0m \u001b[38;5;124;03m    This turns a lazy Dask collection into its in-memory equivalent.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    374\u001b[0m \u001b[38;5;124;03m    dask.compute\u001b[39;00m\n\u001b[1;32m    375\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 376\u001b[0m     (result,) \u001b[38;5;241m=\u001b[39m compute(\u001b[38;5;28mself\u001b[39m, traverse\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m    377\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/base.py:664\u001b[0m, in \u001b[0;36mcompute\u001b[0;34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)\u001b[0m\n\u001b[1;32m    661\u001b[0m     postcomputes\u001b[38;5;241m.\u001b[39mappend(x\u001b[38;5;241m.\u001b[39m__dask_postcompute__())\n\u001b[1;32m    663\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m shorten_traceback():\n\u001b[0;32m--> 664\u001b[0m     results \u001b[38;5;241m=\u001b[39m schedule(dsk, keys, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m    666\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m repack([f(r, \u001b[38;5;241m*\u001b[39ma) \u001b[38;5;28;01mfor\u001b[39;00m r, (f, a) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(results, postcomputes)])\n",
      "Cell \u001b[0;32mIn[6], line 20\u001b[0m, in \u001b[0;36m<lambda>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     15\u001b[0m tau: \u001b[38;5;28mfloat\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m3.125e-9\u001b[39m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;66;03m# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\u001b[39;00m\n\u001b[1;32m     18\u001b[0m result_array \u001b[38;5;241m=\u001b[39m lrm_dda\u001b[38;5;241m.\u001b[39mmap_blocks(\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;66;03m# Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\u001b[39;00m\n\u001b[0;32m---> 20\u001b[0m     \u001b[38;5;28;01mlambda\u001b[39;00m x: identify_leading_edge(np\u001b[38;5;241m.\u001b[39msqueeze(x), tau),\n\u001b[1;32m     21\u001b[0m     meta\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mzeros(\u001b[38;5;241m2\u001b[39m, dtype\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mfloat64)\n\u001b[1;32m     22\u001b[0m )\n\u001b[1;32m     23\u001b[0m result \u001b[38;5;241m=\u001b[39m result_array\u001b[38;5;241m.\u001b[39mcompute()\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28mprint\u001b[39m(result)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'identify_leading_edge' is not defined"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "rror(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,783 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 622, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(622, 623, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,800 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 6, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(6, 7, None\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,801 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 606, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(606, 607, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,803 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 617, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(617, 618, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,806 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 530, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(530, 531, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,809 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 614, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(614, 615, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 595, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(595, 596, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 598, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(598, 599, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,814 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 576, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(576, 577, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,821 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 55, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(55, 56, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,822 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 587, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(587, 588, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,825 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 549, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(549, 550, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,826 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 568, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(568, 569, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,829 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 538, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(538, 539, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,831 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 557, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(557, 558, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,835 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 546, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(546, 547, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "2024-10-05 22:01:22,910 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Traceback (most recent call last):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Process Dask Worker process (from Nanny):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "# Use a local cluster, and process only - CPU intensive, GIL pb with threads\n",
    "cluster: dask.distributed.LocalCluster = dask.distributed.LocalCluster(processes=True)\n",
    "client: dask.distributed.Client = dask.distributed.Client(cluster)\n",
    "\n",
    "# Process only 1 file\n",
    "ds = xr.open_dataset(f\"{DOWNLOAD_DIR}/S3B_SR_2_WAT____20240923T002358_20240923T002431_20240923T015119_0033_098_016______MAR_O_NR_005.SEN3/{MEASUREMENTS_FILENAME}\")\n",
    "ds.close()\n",
    "\n",
    "print(ds)\n",
    "lrm_da = ds[\"waveform_20_plrm_ku\"]\n",
    "\n",
    "# I know this is very in efficient, to have few kB of data to process in dask -> MBs is the usual dask standard\n",
    "# But it is for map_blocks learning purpose\n",
    "lrm_dda = da.from_array(lrm_da, chunks=(1, 128))\n",
    "tau: float = 3.125e-9\n",
    "\n",
    "# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\n",
    "result_array = lrm_dda.map_blocks(\n",
    "    # Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\n",
    "    lambda x: identify_leading_edge(np.squeeze(x), tau),\n",
    "    meta=np.zeros(2, dtype=np.float64)\n",
    ")\n",
    "result = result_array.compute()\n",
    "print(result)\n",
    "\n",
    "client.close()\n",
    "cluster.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
