{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5d297a31-494d-4ee3-ac0a-58afc007959f",
   "metadata": {},
   "source": [
    "## Identify leading edge\n",
    "\n",
    "This is a test notebook, for me to make a few tests about leading edge detection on along track altimeter Waveforms.\n",
    "\n",
    "The algo is an implementation of the leading edge detection of WHALES algo described in [this document](https://climate.esa.int/sites/default/files/Sea_State_cci_ATBD_v1.1-signed_0.pdf)\n",
    "\n",
    "For now it is random code, with 0 optims consideration: \n",
    "- for loops in numpy arrays instead of using vectorized numpy functions (derivative)\n",
    "- dask distribution with micro chunks is inefficient\n",
    "\n",
    "But the objective here is to load zarr time ranges that have not been processed (zarr partitionned by time range) and to use chunks defined at zarr level. \n",
    "Zarr variable we use as input is *waveform_20_plrm_ku*, which is 20Hz data, with 128 waveform points per waveform. This variable is 2D, indexed by *time_20_ku* (timestamp of the waveform) and *echo_sample_ind* (index of each of the 128 waveform data points).\n",
    "Idealy, chunks are in the MBs range, so that it is worth using dask.\n",
    "\n",
    "On each chunk, we have multiple waveforms on which we apply the leading_edge detection algorithm sequentially, to derive *startgate* and *stopgate* attributes of the waveform. And chunks are processed in parallel via dask.\n",
    "\n",
    "Then the *startgate* and *stopgate* are stored to variables *waveform_20_plrm_ku_startgate* and *waveform_20_plrm_ku_stopgate* which are tied to index *time_20_ku*.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "24695572-e042-434d-b2f2-108357be01e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "import dask\n",
    "import dask.distributed\n",
    "import dask.array as da\n",
    "\n",
    "from typing import Tuple, Optional\n",
    "\n",
    "import eumdac.collection\n",
    "\n",
    "sys.path.append(os.path.abspath('..'))\n",
    "from src.connectors.eumdac_connector import EumdacConnector\n",
    "from utils.opensearch_query_formatter import OpenSearchQueryFormatter"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef01e5a7-d250-490b-9225-d0123ac0c75a",
   "metadata": {},
   "source": [
    "### The Leading edge detection algo - to apply on one waveform\n",
    "\n",
    "To refacto - use numpy better"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "18921e91-faa5-4122-a4da-4d35122ff2d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def identify_leading_edge(waveform: np.array, tau: float) -> np.array:\n",
    "    \"\"\"\n",
    "    Identify the startgate and stopgate of a waveform.\n",
    "    From algo described here: https://climate.esa.int/sites/default/files/Sea_State_cci_ATBD_v1.1-signed_0.pdf\n",
    "\n",
    "    :param np.array waveform: numpy array of waveform values\n",
    "    :param float tau: time spacing between consecutive gates in seconds\n",
    "    :return: 1D np.array with 2 values:\n",
    "      - startgate: index of the start gate (Optional[int])\n",
    "      - stopgate: index of the stop gate (Optional[int])\n",
    "    :rtype: np.array\n",
    "\n",
    "    \"\"\"\n",
    "    res: np.array = np.array([-1.0, -1.0], dtype=np.float64)\n",
    "    try:\n",
    "        # The waveform is normalised with normalisation factor N, \n",
    "        # where N = 1.3 * median(waveform)\n",
    "        N: float = 1.3 * np.median(waveform)\n",
    "        normalized_waveform: np.ndarray = waveform / N\n",
    "    \n",
    "        # The leading edge starts when the normalised waveform has a \n",
    "        # rise of 0.01 units compared to the previous gate (startgate)\n",
    "        startgate: int | None = None\n",
    "        for i in range(1, len(normalized_waveform)):\n",
    "            if normalized_waveform[i] - normalized_waveform[i-1] >= 0.01:\n",
    "                startgate = i\n",
    "                break\n",
    "    \n",
    "        if startgate is None:\n",
    "            return res  # No valid startgate found\n",
    "    \n",
    "        # At this point, the leading edge is considered valid if, for at least four gates \n",
    "        # after startgate, it does not decrease below 0.1 units (10% of the normalised power).\n",
    "        valid_leading_edge: bool = (\n",
    "            startgate + 4 < len(normalized_waveform) and\n",
    "            np.all(normalized_waveform[startgate:startgate + 5] >= 0.1)\n",
    "        )\n",
    "    \n",
    "        if not valid_leading_edge:\n",
    "            return res  # Leading edge is not valid\n",
    "    \n",
    "        # The end of the leading edge (stopgate) is fixed at the first gate \n",
    "        # in which the derivative changes sign (i.e. the signal start decreasing \n",
    "        # and the trailing edge begins), if the change of sign is kept \n",
    "        # for the following 3 gates.\n",
    "        stopgate: int | None = None\n",
    "        for i in range(startgate + 1, len(normalized_waveform) - 3):\n",
    "            # Calculate the derivative\n",
    "            derivative: float = normalized_waveform[i + 1] - normalized_waveform[i]\n",
    "            if derivative < 0:  # Start of decrease\n",
    "                # Check if the derivative stays negative for the next 3 gates\n",
    "                if (normalized_waveform[i + 2] - normalized_waveform[i + 1] < 0 and\n",
    "                    normalized_waveform[i + 3] - normalized_waveform[i + 2] < 0):\n",
    "                    stopgate = i\n",
    "                    break\n",
    "    \n",
    "        res = np.array([startgate, stopgate], dtype=np.float64)\n",
    "        print(res)\n",
    "        return res\n",
    "    except:\n",
    "        return res"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "60c64a07-31ef-4afd-b595-e9901fce297d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(17,)\n",
      "[ 4. 10.]\n",
      "Startgate: 4.0, Stopgate: 10.0\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    # Simulated waveform data\n",
    "    waveform: np.ndarray = np.array([0.0, 0.0, 0.0, 0.0001, 0.0015, 0.002, 0.004, 0.01, 0.02, 0.05, 0.15, 0.1, 0.08, 0.07, 0.03, 0.01, 0.0])\n",
    "    tau: float = 3.125e-9  # Time spacing in seconds\n",
    "\n",
    "    res = identify_leading_edge(waveform, tau)\n",
    "    print(res)\n",
    "    startgate, stopgate = res\n",
    "    print(f\"Startgate: {startgate}, Stopgate: {stopgate}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "abfb26f7-0dbf-4d6e-b0b1-d3df41f8f091",
   "metadata": {},
   "source": [
    "### Download datasets containing waveform (Sentinel 3) and store them to zarr\n",
    "\n",
    "**TODO**: zarr storage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d36cabdd-5c67-4fc3-aefe-e17415ce74f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Local mode: processing every 50th product to debug faster\n",
      "%s matching products found 1\n",
      "Listed products are: %s ['S3B_SR_2_WAT____20240923T002358_20240923T002431_20240923T015119_0033_098_016______MAR_O_NR_005.SEN3']\n",
      "Downloading products (dask parallelized)...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 43047 instead\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "COLLECTION_ID: str = \"EO:EUM:DAT:0415\"\n",
    "DOWNLOAD_DIR: str = \"/tmp/products\"\n",
    "MEASUREMENTS_FILENAME: str = \"enhanced_measurement.nc\"\n",
    "INDEX_DIMENSION: str = \"time_01\"\n",
    "download_dir: str = os.path.join(os.getcwd(), DOWNLOAD_DIR)\n",
    "\n",
    "connector: EumdacConnector = EumdacConnector()\n",
    "datastore: eumdac.datastore.DataStore = connector.datastore\n",
    "\n",
    "# Query a few data files for Sentinel3A and 3B SRAL (Level2 data)\n",
    "opensearch_query: str = OpenSearchQueryFormatter(\n",
    "    query_params={\n",
    "        \"pi\": COLLECTION_ID,\n",
    "        \"dtstart\": \"2024-09-23T00:20:00Z\",\n",
    "        \"dtend\": \"2024-09-23T00:30:00Z\",\n",
    "    }\n",
    ").format()\n",
    "products: eumdac.collection.SearchResults = datastore.opensearch(query=opensearch_query)\n",
    "product_ids: list[str] = [str(x) for x in products]\n",
    "# If in local mode, process only a subset of the products for faster execution\n",
    "if os.getenv(\"LOCAL_MODE\", \"1\"):\n",
    "    print(\"Local mode: processing every 50th product to debug faster\")\n",
    "    product_ids = product_ids[::50]\n",
    "print(\"%s matching products found\", len(product_ids))\n",
    "print(\"Listed products are: %s\", product_ids)\n",
    "\n",
    "# Download files - benefits of dask parallelization\n",
    "print(\"Downloading products (dask parallelized)...\")\n",
    "downloaded_folders: list[str] = connector.download_products(\n",
    "    COLLECTION_ID, product_ids, download_dir, MEASUREMENTS_FILENAME\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be87cf22-6554-4a22-bbb9-729de691f897",
   "metadata": {},
   "source": [
    "### WIP\n",
    "\n",
    "To refacto 100%: load from zarr, process bigger chunks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "998c9dc2-0073-4f46-a041-8d557fb91de5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 41935 instead\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<xarray.Dataset> Size: 3MB\n",
      "Dimensions:                                        (time_01: 33,\n",
      "                                                    time_20_ku: 628,\n",
      "                                                    time_20_c: 628,\n",
      "                                                    echo_sample_ind: 128)\n",
      "Coordinates:\n",
      "  * time_01                                        (time_01) datetime64[ns] 264B ...\n",
      "  * time_20_ku                                     (time_20_ku) datetime64[ns] 5kB ...\n",
      "  * time_20_c                                      (time_20_c) datetime64[ns] 5kB ...\n",
      "  * echo_sample_ind                                (echo_sample_ind) int8 128B ...\n",
      "    lat_01                                         (time_01) float64 264B ...\n",
      "    lon_01                                         (time_01) float64 264B ...\n",
      "    lat_20_ku                                      (time_20_ku) float64 5kB ...\n",
      "    lon_20_ku                                      (time_20_ku) float64 5kB ...\n",
      "    lat_20_c                                       (time_20_c) float64 5kB ...\n",
      "    lon_20_c                                       (time_20_c) float64 5kB ...\n",
      "Data variables: (12/392)\n",
      "    UTC_day_01                                     (time_01) datetime64[ns] 264B ...\n",
      "    UTC_sec_01                                     (time_01) float64 264B ...\n",
      "    UTC_day_20_ku                                  (time_20_ku) datetime64[ns] 5kB ...\n",
      "    UTC_sec_20_ku                                  (time_20_ku) float64 5kB ...\n",
      "    UTC_day_20_c                                   (time_20_c) datetime64[ns] 5kB ...\n",
      "    UTC_sec_20_c                                   (time_20_c) float64 5kB ...\n",
      "    ...                                             ...\n",
      "    num_20hz_meas_01_ku                            (time_01) float32 132B ...\n",
      "    num_20hz_meas_01_c                             (time_01) float32 132B ...\n",
      "    orbit_type_01                                  (time_01) float32 132B ...\n",
      "    waveform_qual_ice_20_ku                        (time_20_ku) float32 3kB ...\n",
      "    iono_cor_alt_filtered_01_ku                    (time_01) float64 264B ...\n",
      "    iono_cor_alt_filtered_01_plrm_ku               (time_01) float64 264B ...\n",
      "Attributes: (12/64)\n",
      "    Conventions:                                 CF-1.6\n",
      "    title:                                       IPF SRAL/MWR Level 2 Measure...\n",
      "    mission_name:                                Sentinel 3B\n",
      "    altimeter_sensor_name:                       SRAL\n",
      "    radiometer_sensor_name:                      MWR\n",
      "    gnss_sensor_name:                            GNSS\n",
      "    ...                                          ...\n",
      "    algo_bias_wind_speed_sig0_sar_ku_added:      -0.0008\n",
      "    algo_bias_wind_speed_2p_sig0_sar_ku_added:   2.7735\n",
      "    algo_bias_wind_speed_2p_swh_sar_ku_added:    0.0\n",
      "    algo_bias_wind_speed_sig0_plrm_ku_added:     0.02795\n",
      "    algo_bias_wind_speed_2p_sig0_plrm_ku_added:  2.8071\n",
      "    algo_bias_wind_speed_2p_swh_plrm_ku_added:   0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-05 22:01:19,635 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 95, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(95, 96, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,641 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 90, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(90, 91, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,646 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 86, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(86, 87, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,651 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 85, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(85, 86, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,659 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 83, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(83, 84, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,661 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 84, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(84, 85, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,667 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 82, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(82, 83, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,697 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 74, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(74, 75, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,699 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 72, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(72, 73, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,712 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 93, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(93, 94, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,714 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 87, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(87, 88, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,714 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 88, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(88, 89, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,716 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 81, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(81, 82, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,719 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 68, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(68, 69, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,719 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 73, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(73, 74, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 98, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(98, 99, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 96, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(96, 97, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,721 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 8, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(8, 9, None\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,722 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 76, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(76, 77, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,723 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 65, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(65, 66, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,725 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 70, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(70, 71, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,731 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 625, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(625, 626, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,735 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 619, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(619, 620, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,737 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 62, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(62, 63, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,747 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 608, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(608, 609, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,769 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 71, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(71, 72, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,776 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 63, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(63, 64, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,777 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 627, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(627, 628, \n",
      "kwargs:    {}\n",
      "Exception: 'NameE"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'identify_leading_edge' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 23\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;66;03m# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\u001b[39;00m\n\u001b[1;32m     18\u001b[0m result_array \u001b[38;5;241m=\u001b[39m lrm_dda\u001b[38;5;241m.\u001b[39mmap_blocks(\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;66;03m# Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\u001b[39;00m\n\u001b[1;32m     20\u001b[0m     \u001b[38;5;28;01mlambda\u001b[39;00m x: identify_leading_edge(np\u001b[38;5;241m.\u001b[39msqueeze(x), tau),\n\u001b[1;32m     21\u001b[0m     meta\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mzeros(\u001b[38;5;241m2\u001b[39m, dtype\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mfloat64)\n\u001b[1;32m     22\u001b[0m )\n\u001b[0;32m---> 23\u001b[0m result \u001b[38;5;241m=\u001b[39m result_array\u001b[38;5;241m.\u001b[39mcompute()\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28mprint\u001b[39m(result)\n\u001b[1;32m     26\u001b[0m client\u001b[38;5;241m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/base.py:376\u001b[0m, in \u001b[0;36mDaskMethodsMixin.compute\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m    352\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcompute\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    353\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Compute this dask collection\u001b[39;00m\n\u001b[1;32m    354\u001b[0m \n\u001b[1;32m    355\u001b[0m \u001b[38;5;124;03m    This turns a lazy Dask collection into its in-memory equivalent.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    374\u001b[0m \u001b[38;5;124;03m    dask.compute\u001b[39;00m\n\u001b[1;32m    375\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 376\u001b[0m     (result,) \u001b[38;5;241m=\u001b[39m compute(\u001b[38;5;28mself\u001b[39m, traverse\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m    377\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/base.py:664\u001b[0m, in \u001b[0;36mcompute\u001b[0;34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)\u001b[0m\n\u001b[1;32m    661\u001b[0m     postcomputes\u001b[38;5;241m.\u001b[39mappend(x\u001b[38;5;241m.\u001b[39m__dask_postcompute__())\n\u001b[1;32m    663\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m shorten_traceback():\n\u001b[0;32m--> 664\u001b[0m     results \u001b[38;5;241m=\u001b[39m schedule(dsk, keys, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m    666\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m repack([f(r, \u001b[38;5;241m*\u001b[39ma) \u001b[38;5;28;01mfor\u001b[39;00m r, (f, a) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(results, postcomputes)])\n",
      "Cell \u001b[0;32mIn[6], line 20\u001b[0m, in \u001b[0;36m<lambda>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     15\u001b[0m tau: \u001b[38;5;28mfloat\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m3.125e-9\u001b[39m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;66;03m# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\u001b[39;00m\n\u001b[1;32m     18\u001b[0m result_array \u001b[38;5;241m=\u001b[39m lrm_dda\u001b[38;5;241m.\u001b[39mmap_blocks(\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;66;03m# Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\u001b[39;00m\n\u001b[0;32m---> 20\u001b[0m     \u001b[38;5;28;01mlambda\u001b[39;00m x: identify_leading_edge(np\u001b[38;5;241m.\u001b[39msqueeze(x), tau),\n\u001b[1;32m     21\u001b[0m     meta\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mzeros(\u001b[38;5;241m2\u001b[39m, dtype\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39mfloat64)\n\u001b[1;32m     22\u001b[0m )\n\u001b[1;32m     23\u001b[0m result \u001b[38;5;241m=\u001b[39m result_array\u001b[38;5;241m.\u001b[39mcompute()\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28mprint\u001b[39m(result)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'identify_leading_edge' is not defined"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "rror(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,783 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 622, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(622, 623, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,800 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 6, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(6, 7, None\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,801 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 606, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(606, 607, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,803 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 617, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(617, 618, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,806 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 530, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(530, 531, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,809 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 614, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(614, 615, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 595, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(595, 596, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 598, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(598, 599, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,814 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 576, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(576, 577, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,821 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 55, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(55, 56, No\n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,822 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 587, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(587, 588, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,825 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 549, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(549, 550, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,826 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 568, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(568, 569, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,829 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 538, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(538, 539, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,831 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 557, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(557, 558, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "2024-10-05 22:01:19,835 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       ('lambda-c9198e16ddca1e5fdea9fc365bdbf830', 546, 0)\n",
      "State:     executing\n",
      "Function:  subgraph_callable-369879cfed3b0dbf39fe955e1502bb9d\n",
      "args:      (<xarray.DataArray 'waveform_20_plrm_ku' (time_20_c: 628, echo_sample_ind: 128)> Size: 643kB\n",
      "array([[ 9.421,  8.474,  5.44 , ..., 26.968, 25.114, 12.534],\n",
      "       [ 6.666,  4.541,  3.079, ..., 14.956, 10.474,  8.22 ],\n",
      "       [ 8.677,  6.729,  4.366, ..., 20.98 , 17.217, 16.225],\n",
      "       ...,\n",
      "       [23.719, 22.934, 21.37 , ..., 38.054, 41.226, 28.066],\n",
      "       [26.14 , 24.18 , 20.693, ..., 41.975, 39.995, 33.043],\n",
      "       [29.138, 23.461, 18.273, ..., 38.704, 26.502, 27.926]])\n",
      "Coordinates:\n",
      "  * time_20_c        (time_20_c) datetime64[ns] 5kB 2024-09-23T00:23:57.53276...\n",
      "  * echo_sample_ind  (echo_sample_ind) int8 128B 0 1 2 3 4 ... 124 125 126 127\n",
      "    lat_20_c         (time_20_c) float64 5kB -65.15 -65.16 ... -67.0 -67.0\n",
      "    lon_20_c         (time_20_c) float64 5kB 125.2 125.2 125.2 ... 123.2 123.2\n",
      "Attributes:\n",
      "    long_name:  Waveform samples (I2+Q2) : 20 Hz Plrm Ku band\n",
      "    units:      count\n",
      "    comment:    LRM mode Ku and C bands: the echo is corrected for the GPRW e..., (slice(546, 547, \n",
      "kwargs:    {}\n",
      "Exception: 'NameError(\"name \\'identify_leading_edge\\' is not defined\")'\n",
      "Traceback: '  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/optimization.py\", line 1001, in __call__\\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 157, in get\\n    result = _execute_task(task, cache)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/dask/core.py\", line 127, in _execute_task\\n    return func(*(_execute_task(a, cache) for a in args))\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/tmp/ipykernel_3165/3513934251.py\", line 20, in <lambda>\\n'\n",
      "\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "2024-10-05 22:01:22,910 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Traceback (most recent call last):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Process Dask Worker process (from Nanny):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "2024-10-05 22:01:22,911 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 977, in run\n",
      "    await worker.finished()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/site-packages/distributed/nanny.py\", line 1015, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/abonnin/anaconda3/envs/sentinel3-sral-demo/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "# Use a local cluster, and process only - CPU intensive, GIL pb with threads\n",
    "cluster: dask.distributed.LocalCluster = dask.distributed.LocalCluster(processes=True)\n",
    "client: dask.distributed.Client = dask.distributed.Client(cluster)\n",
    "\n",
    "# Process only 1 file\n",
    "ds = xr.open_dataset(f\"{DOWNLOAD_DIR}/S3B_SR_2_WAT____20240923T002358_20240923T002431_20240923T015119_0033_098_016______MAR_O_NR_005.SEN3/{MEASUREMENTS_FILENAME}\")\n",
    "ds.close()\n",
    "\n",
    "print(ds)\n",
    "lrm_da = ds[\"waveform_20_plrm_ku\"]\n",
    "\n",
    "# I know this is very in efficient, to have few kB of data to process in dask -> MBs is the usual dask standard\n",
    "# But it is for map_blocks learning purpose\n",
    "lrm_dda = da.from_array(lrm_da, chunks=(1, 128))\n",
    "tau: float = 3.125e-9\n",
    "\n",
    "# identify_leading_edge(waveform: np.ndarray, tau: float) -> np.array 1D with 2 values\n",
    "result_array = lrm_dda.map_blocks(\n",
    "    # Squeeze the 2D array (1, 128) to 1D (128) as expected by 'identify_leading_edge'\n",
    "    lambda x: identify_leading_edge(np.squeeze(x), tau),\n",
    "    meta=np.zeros(2, dtype=np.float64)\n",
    ")\n",
    "result = result_array.compute()\n",
    "print(result)\n",
    "\n",
    "client.close()\n",
    "cluster.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
